/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author usuario
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Bcalcular = new javax.swing.JButton();
        Tvalor2 = new javax.swing.JTextField();
        text2 = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        Tvalor1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Lresultado = new javax.swing.JLabel();
        Rsuma = new javax.swing.JRadioButton();
        Rresta = new javax.swing.JRadioButton();
        Rmultiplicacion = new javax.swing.JRadioButton();
        Rdivision = new javax.swing.JRadioButton();
        Robot = new javax.swing.JLabel();
        Comentario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        Bcalcular.setBackground(new java.awt.Color(153, 153, 153));
        Bcalcular.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        Bcalcular.setForeground(new java.awt.Color(255, 255, 255));
        Bcalcular.setText("Calcular");
        Bcalcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bcalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BcalcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BcalcularMouseExited(evt);
            }
        });
        Bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcalcularActionPerformed(evt);
            }
        });

        Tvalor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Tvalor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tvalor2.setMinimumSize(new java.awt.Dimension(64, 27));

        text2.setBackground(new java.awt.Color(153, 255, 255));
        text2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2.setText("Dato 1");
        text2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        text.setBackground(new java.awt.Color(102, 255, 255));
        text.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Dato 2");
        text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        text.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tvalor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Tvalor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tvalor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tvalor2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(text2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tvalor1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Bcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tvalor2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(Tvalor1))
                .addGap(18, 18, 18)
                .addComponent(Bcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 410, 220));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lresultado.setBackground(new java.awt.Color(204, 255, 255));
        Lresultado.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        Lresultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lresultado.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 410, -1));

        buttonGroup1.add(Rsuma);
        Rsuma.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        Rsuma.setText("Suma");
        Rsuma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rsuma.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Rsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RsumaActionPerformed(evt);
            }
        });
        getContentPane().add(Rsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 120, -1));

        buttonGroup1.add(Rresta);
        Rresta.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        Rresta.setText("Resta");
        Rresta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Rresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 98, 30));

        buttonGroup1.add(Rmultiplicacion);
        Rmultiplicacion.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        Rmultiplicacion.setText("Multiplicacion");
        Rmultiplicacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RmultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(Rmultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 240, -1));

        buttonGroup1.add(Rdivision);
        Rdivision.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        Rdivision.setText("Division");
        Rdivision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Rdivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 160, 30));

        Robot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/Bot.png"))); // NOI18N
        Robot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RobotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RobotMouseExited(evt);
            }
        });
        getContentPane().add(Robot, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        Comentario.setBackground(new java.awt.Color(255, 255, 255));
        Comentario.setFont(new java.awt.Font("Sitka Text", 2, 24)); // NOI18N
        Comentario.setForeground(new java.awt.Color(255, 0, 0));
        Comentario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comentario.setToolTipText("");
        Comentario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 320, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/ilustracion-vector-fondo-aritmetico-patrones-fisuras-numeros-operaciones-matematicas_449806-433.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -560, 1040, 870));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/ilustracion-vector-fondo-aritmetico-patrones-fisuras-numeros-operaciones-matematicas_449806-433.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tvalor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tvalor1ActionPerformed

    private void BcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcalcularActionPerformed
        float num1 = 0, num2 = 0, total = 0;
        num1 = Float.parseFloat(Tvalor1.getText());
        num2 = Float.parseFloat(Tvalor2.getText());
        if (Rsuma.isSelected()) {
            total = num1 + num2;
        } else if (Rresta.isSelected()) {
            total = num1 - num2;
        } else if (Rmultiplicacion.isSelected()) {
            total = num1 * num2;
        } else if (Rdivision.isSelected()) {
            total = num1 / num2;
        }
        Lresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_BcalcularActionPerformed

    private void BcalcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalcularMouseExited
    
    }//GEN-LAST:event_BcalcularMouseExited

    private void BcalcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalcularMouseEntered
       
    }//GEN-LAST:event_BcalcularMouseEntered

    private void RmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RmultiplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RmultiplicacionActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Rsuma.setSelected(true);
    }//GEN-LAST:event_formWindowActivated

    private void RsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RsumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RsumaActionPerformed

    private void RobotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RobotMouseEntered
        Comentario.setText("WOW !!! "
       + "Ingrese los datos");        // TODO add your handling code here:
    }//GEN-LAST:event_RobotMouseEntered

    private void RobotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RobotMouseExited
        Comentario.setText("");
    }//GEN-LAST:event_RobotMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcalcular;
    private javax.swing.JLabel Comentario;
    private javax.swing.JLabel Lresultado;
    private javax.swing.JRadioButton Rdivision;
    private javax.swing.JRadioButton Rmultiplicacion;
    private javax.swing.JLabel Robot;
    private javax.swing.JRadioButton Rresta;
    private javax.swing.JRadioButton Rsuma;
    private javax.swing.JTextField Tvalor1;
    private javax.swing.JTextField Tvalor2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text2;
    // End of variables declaration//GEN-END:variables
}
